### PR TITLE
Fix completing 1 post completes all posts

### LINKED ISSUE #13: Completing 1 post completes all posts
### Reproduction Steps

+ Install & activate Lite LMS
+ Create 3 pages. 
+ Add Lite LMS block
+ Add Incomplete message and complete message
+ Complete 1 page on the front end
+ Notice all pages complete

View this test environment: https://lms-lite-test.myliftersite.com/

### Expected Behavior

+ Completing the block on one post would only complete the block on the one post, not all completable posts

### Actual Behavior

+ All posts with Lite LMS complete when 1 complete button is clicked

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

This issue has be recreated:
+ [ ] Locally
+ [X] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
Chrome
+ Operating System name and version
OSX
+ Device name and version (if applicable)
MacBook Pro

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
fixes #13 

@thomasplevy I think this (or kinda of) is what the client js asks for, right?!

### CODE REVIEW

File: src/js/editor.js [hunk 1]
```diff
@@ -26,9 +27,13 @@ registerBlockType( 'llms-lite-lms/progress-tracker', {
 		allowReset: {
 			type: 'boolean',
 			default: false,
+		},
+		postId: {
+			type: 'integer',
+			default: null,
```
Comment (thomasplevy) [inline src/js/editor.js]:
```suggestion
```

I'm pretty sure that this is unnecessary to explicitly define as `null`

File: src/js/editor/edit.js [hunk 2]
```diff
@@ -54,19 +55,21 @@ export default function ( { className, attributes, setAttributes } ) {
 		className += ' has-complete-msg';
 	}
 
+	setAttributes( {postId: select( 'core/editor' ).getCurrentPostId()} );
```
Comment (thomasplevy) [inline src/js/editor/edit.js]: My experience with these data calls is that on page load, if the block exists in the editor, it'll make the calls when the block initializes and the postId may return null, to avoid multiple unnecessary sets with empty data we can check for the presence of the id and only set it when it exists

Also, once it's been set the postId isn't going to change so we should be able to make this a one-time thing.

```suggestion
	let { postId } = attributes;
	postId = postId || select( 'core/editor' ).getCurrentPostId();
	if ( postId && ! attributes.postId ) {
		setAttributes( { postId } );
	}
```

Comment (thomasplevy) [reply src/js/editor/edit.js]: I didn't test this.

**Review by thomasplevy — CHANGES_REQUESTED** [review]

File: src/js/editor/edit.js (hunk 2 above)
Comment (eri-trabiccolo) [reply src/js/editor/edit.js]: Ok for not setting it when null, BUT I wanted it to be set not only once because I was thinking about copy pasting a block in another page, and in that case I wanted it to get the "new page" id. Although I'm going to test if your solution works fine in this case <3 thanks!

Comment (eri-trabiccolo) [reply src/js/editor/edit.js]: Ok @thomasplevy just tested that with your code above if I copy this block into another page and save then the block retains the previous post-id attribute... So maybe we set it only if the current post id is not null and different from the saved attribute... agreed?

Comment (thomasplevy) [reply src/js/editor/edit.js]: hadn't thought about that, good call
